#!/bin/bash

#
# usage:
#	$ ./case <case>
#

case=$1

dim=3
numBC=1
BC="5 6"
vec="0 0 10"  # distance vector bw parallel BC's

rm -f *ma2 *re2

./g2n << DOF
$dim
$case
$numBC
$BC
$vec
DOF

tol="0.2"
#tol="0.1"
#tol="0.01"

./gmp << DOF
$case
$tol
DOF
